### ISSUE TITLE
Sometimes there are black lines below or at the right side of a video

### ISSUE THREAD

**Issue by WesselKroos** [WesselKroos/youtube-ambilight#136]
**Describe the bug**
Depending on the size of the video player there is a chance that a black line appears at the bottom, at the right side or at both the bottom and the right side of the video:

**To Reproduce**
1. You need a 1000/2000/3000/4000 series NVidia graphics card with the NVidia Geforce Game Ready driver version 472.12 or higher. Or an Intel Tigerlake integrated GPU. (There might be more GPU's that have this bug. But we don't know them all yet.)
2. Go to a video page
3. Resize the browser until black lines appear

**Expected behavior**
No lines

**Screenshots**
![image](https://user-images.githubusercontent.com/31220528/197395322-a200c5af-31e3-423e-a37e-1bae9cc8e109.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Browser version: 105, 106
 - Extension version: 0.36.31

**Comment by WesselKroos** [comment]
**Workarounds**
- Resize the video player to another width/height until the lines are gone
- Create a Chromium (Chrome, Opera, Edge) shortcut with the flag --disable-direct-composition-video-overlays

**Todo**
- [ ] Report the bug to the Chromium developers
- [ ] Find a workaround that does not require a shortcut with a flag

**Comment by WesselKroos** [comment]
@Nirgranth Can you also reproduce this bug? Because you were also able to reproduce issue #97

**Comment by Nirgranth** [comment]
Yes i have noticed it, i thought it was just me

**Comment by WesselKroos** [comment]
Todo:
- [ ] Check if this bug still happens after the workaround for bug #150 is released

**Comment by WesselKroos** [comment]
@Nirgranth This is now fixed in version 2.37.2 (Already released to Opera but in review for Edge and Chrome)
