### ISSUE TITLE
Improve performance on low-end devices

### ISSUE THREAD

**Issue by WesselKroos** [WesselKroos/youtube-ambilight#64]
**Todo:**
- [x] Remove extension from the Firefox Addons store because of worse performance in Firefox
- [x] Replace the most important Context2D instances with WebGLRenderingContext
- [x] Implement a single canvas projector via WebGL
- [x] Implement canvas blur
- [x] Resolution setting
- [x] Antialiasing
- [x] WebGL setting

***Further improvements in #111***

Benefits:
- Potential GPU usage reduction by using WebGL: 60% -> 30% on Chromium and even more on Firefox. 
The first tests on a laptop in Chrome are showing promising frametimes (GPU usage went from 80% to 30%):

![image](https://user-images.githubusercontent.com/31220528/157762586-f5e76daf-b354-462f-9e6f-31f7e8e670fe.png)

- [Cut-off css blur workaround](https://bugs.chromium.org/p/chromium/issues/detail?id=1123708) can be removed 
- Removes flickering while scrolling
- Removes flickering antialiasing bug
